name: Build Docker Images

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    name: ZeroTierOne Moon
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest ZeroTierOne Version
        id: ZeroTierOne
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: zerotier/ZeroTierOne
          excludes: "prerelease, draft"

      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            ZT_VERSION=${{ steps.ZeroTierOne.outputs.release }}
          platforms: linux/amd64,linux/ppc64le,linux/s390x,linux/arm32v7,linux/arm64v8
          push: ${{ github.event_name != 'pull_request' }}
          tags: anerg/zerotier-moon:latest, anerg/zerotier-moon:${{ steps.ZeroTierOne.outputs.release }}
